### ISSUE TITLE
Java 1.7 support?

### ISSUE THREAD

**Issue by dan7800** [ksen007/janala2#3]
Does the application work with .class files compiled with 1.7?

Whenever I try to examine a simple HelloWorld have file compiled in 1.7, I get a message

Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 24
Exception Details:
  Location:
    HelloWorld.<init>()V @18: invokespecial
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 0304 03b8 0022 2a04 0412 2312 2412 25b8
    0000010: 0029 b700 01a7 0007 b800 2cbf b800 2fb8
    0000020: 0032 0504 b800 36b1                    
  Exception Handler Table:
    bci [18, 24] => handler: 24

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
	at java.lang.Class.getMethod0(Class.java:2813)
	at java.lang.Class.getMethod(Class.java:1663)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)

However, when I test out the same HelloWorld code compiled in 1.6, everything seems to work fine.

**Comment by zhihan** [comment]
You can try use the updated version which supports java-8. Let me know if you run into any problems.
https://github.com/zhihan/janala2-gradle

**Comment by zhihan** [comment]
Java 8 and Java 7 are now supported.
